name: Publish Package

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Publish to npm
        run: yarn publish:npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: cd ..
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn publish:gpr
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
